let chamados=JSON.parse(localStorage.getItem("chamados"))||[];let numero=Number(localStorage.getItem("numeroChamado"))||1;let usuarioAtual="";
function entrar(){let u=document.getElementById("usuario").value.trim(),s=document.getElementById("senha").value;if((u==="funcionario"||u==="tecnico")&&s==="1234"){usuarioAtual=u;document.getElementById("login").classList.add("hidden");document.getElementById("sistema").classList.remove("hidden");document.getElementById("areaFuncionario").classList.toggle("hidden",u!=="funcionario");document.getElementById("areaTecnico").classList.toggle("hidden",u!=="tecnico");if(u==="tecnico")listar()}else alert("Usuário ou senha inválidos.")}
function sair(){location.reload()}
function criarChamado(){if(usuarioAtual!=="funcionario")return;let categoria=document.getElementById("categoria").value,prioridade=document.getElementById("prioridade").value,titulo=document.getElementById("titulo").value.trim(),descricao=document.getElementById("descricao").value.trim();if(!categoria||!prioridade||!titulo||!descricao){alert("Preencha todos os campos.");return}let c={id:numero++,categoria,prioridade,titulo,descricao,status:"Aberto",responsavel:"Não definido",historico:["Chamado criado pelo funcionário"]};chamados.push(c);salvar();document.getElementById("categoria").value="";document.getElementById("prioridade").value="";document.getElementById("titulo").value="";document.getElementById("descricao").value="";alert("Chamado #"+String(c.id).padStart(6,"0")+" criado!")}
function listar(){if(usuarioAtual!=="tecnico")return;let lista=document.getElementById("lista");if(!chamados.length){lista.innerHTML="<p>Nenhum chamado aberto.</p>";return}lista.innerHTML=chamados.map(c=>`<div class="chamado"><h3>#${String(c.id).padStart(6,"0")} - ${esc(c.titulo)}</h3><p>${esc(c.descricao)}</p><p><b>Categoria:</b> ${esc(c.categoria)}<br><b>Prioridade:</b> ${esc(c.prioridade)}<br><b>Status:</b> ${esc(c.status)}<br><b>Responsável:</b> ${esc(c.responsavel)}</p><select class="status" onchange="alterarStatus(${c.id},this.value)"><option ${c.status==="Aberto"?"selected":""}>Aberto</option><option ${c.status==="Em atendimento"?"selected":""}>Em atendimento</option><option ${c.status==="Encerrado"?"selected":""}>Encerrado</option></select><button onclick="responsavel(${c.id})">Definir responsável</button> <button onclick="solucao(${c.id})">Registrar solução</button><details><summary>Histórico</summary><ul>${c.historico.map(h=>"<li>"+esc(h)+"</li>").join("")}</ul></details></div>`).join("")}
function alterarStatus(id,status){if(usuarioAtual!=="tecnico")return;let c=chamados.find(x=>x.id===id);c.status=status;c.historico.push("Status alterado para: "+status);salvar();listar()}
function responsavel(id){if(usuarioAtual!=="tecnico")return;let nome=prompt("Nome do técnico responsável:");if(!nome)return;let c=chamados.find(x=>x.id===id);c.responsavel=nome;c.historico.push("Responsável definido: "+nome);salvar();listar()}
function solucao(id){if(usuarioAtual!=="tecnico")return;let texto=prompt("Informe a solução aplicada:");if(!texto)return;let c=chamados.find(x=>x.id===id);c.solucao=texto;c.status="Encerrado";c.historico.push("Solução registrada: "+texto);c.historico.push("Chamado encerrado");salvar();listar()}
function salvar(){localStorage.setItem("chamados",JSON.stringify(chamados));localStorage.setItem("numeroChamado",numero)}
function esc(t){return String(t).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}